export declare function use(name: string, app?: string): ((module?: any, modifiers?: any, autoAddParent?: boolean | undefined) => Mods)[];
export * from './basic';
export * from './props';
export * from './dom';
export * from './create';
export * from './format';
export * from './constant';
export * from './validate';
export * from './interceptor';
export * from './with-install';
